# Generated by Django 3.2.11 on 2022-02-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skyuser',
            name='roles',
            field=models.JSONField(null=True),
        ),
    ]
