# Generated by Django 3.2.11 on 2022-02-16 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_skyuser_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skyuser',
            options={'permissions': [('attendance', 'Attendance Manager'), ('parent', 'Parent'), ('big_daddy', 'Master Platform')]},
        ),
    ]
