# Generated by Django 3.2.11 on 2022-02-16 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_auto_20220216_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('begin_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(default=datetime.datetime.now)),
                ('start_time', models.TimeField(blank=True)),
                ('end_time', models.TimeField(blank=True)),
                ('type', models.CharField(default='Tardy Unexcused', max_length=50)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Absence',
            new_name='PlannedAbsence',
        ),
        migrations.DeleteModel(
            name='CheckIn',
        ),
        migrations.DeleteModel(
            name='CheckOut',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
