# Generated by Django 3.2.11 on 2022-02-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_auto_20220216_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='exuse_type',
            field=models.CharField(default='Tardy Unexcused', max_length=50),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
