# Generated by Django 3.2.11 on 2022-02-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_auto_20220218_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
